In [1]:
# This file is to be accompanied with the corresponding Lecture Video. See Moodle/Learn for more info

Why Numpy:

For example:
* Much faster than other structures for many purpose
* Vectorized operations
* Often possible to avoid the need for for-loops
* Effective descriptive statistics and aggregationg/summarizing data
* Memory efficient
* Boolean indexing (we see this with Pandas more)
* Much more reasons...

---

### Initializing ndarray with list

In [2]:
import numpy as np

In [3]:
mylist=[1, 'Tommi', 2,5]
mylist

[1, 'Tommi', 2, 5]

In [4]:
type(mylist)

list

In [5]:
# With Numpy usually we have numbers as elements for the ndarray
myarr = np.array([1, 5, 4, 2])
myarr

array([1, 5, 4, 2])

In [6]:
type(myarr)

numpy.ndarray

## np.array() vs numpy.ndarray


If you take a careful look above, you will notice that we used function array() to create on numpy array of type ndarray

so the fuction np.array([1, 5, 4, 2]) return on object of type ndarray


---

In [7]:
# ufunc for numpy array
myarr.cumsum()

array([ 1,  6, 10, 12])

---

## Commonly used ways to initialize numpy arrays

* array()    # we have already seen that
* asarray()
* arange()   # We have already seen that
* ones()
* ones_like()
* zeros()
* zeros_like()
* empty()
* empty_like()
* full()
* full_like()
* eye()
* identity()


### np.asarray(), Case the input for asarray() method is not of ndarray type

In [8]:
my_list = [1, 2]
my_list

[1, 2]

In [9]:
my_list_asarray = np.asarray(my_list)
my_list_asarray

array([1, 2])

In [10]:
type(my_list_asarray)

numpy.ndarray

If you look at the my_list and my_list_asarray in the cells below 

In [11]:
my_list*2

[1, 2, 1, 2]

In [12]:
my_list_asarray*2

array([2, 4])

### np.asarray(), Case the input for asarray() method IS of ndarray type

In [13]:
my_ndarray = np.array([1, 3, 2, 5])
my_ndarray_asarray = np.asarray(my_ndarray)




In [14]:
#Checking whether those two nd_arrays are actually of the same type!!
my_ndarray is my_ndarray_asarray

True

In [15]:
my_ndarray_asarray[2] = 100

In [16]:
my_ndarray

array([  1,   3, 100,   5])

### np.ones()

In [17]:
my_ones = np.ones([2,3])
my_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

### np.zeros() and np.zeros_like()

In [18]:
my_zeros = np.zeros((3,4))
my_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
my_zeros_like = np.zeros_like(my_ones)
my_zeros_like

array([[0., 0., 0.],
       [0., 0., 0.]])

### np.eye()

In [20]:
my_eye_array = np.eye(5)
my_eye_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
my_identity_array = np.identity(5)
my_identity_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
my_eye_array = np.eye(5, k=2)
my_eye_array

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
# Slicing is frequently utilized with numpy arrays
my_eye_array[ :3, 2:]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])